### ISSUE TITLE
Finish profile page

### ISSUE THREAD

**Issue by d1agnoze** [D-an-gang/Heko#1]
Trong cái profile page(side bar xong bấm vào phần hiện user), 
__Tao mới làm nút log out thôi 😭😭😭__
Làm tiếp form chỉnh sửa thông tin người dùng (__không chỉnh id__): 
* username 👤
* email (xem api updateEmail trong docs) 📨
* mật khẩu (xem api __updatePassword__ hoặc set up template email rồi gửi mail reset password bằng __sendPasswordResetEmail__ api nếu không muốn làm layout) 🔑  
Trước đấy thì test lại đăng ký và đăng nhập xem có lỗi nào không, rồi submit lên issue ✉️

**Comment by CanuXD** [comment]
khong

**Comment by d1agnoze** [comment]
> khong

***dung noi tu khong voi tao***
